@user_api_key = <user_api_key>

### Health check
GET http://localhost:8000/v1/healthy

### Error
GET http://localhost:8000/v1/error

### Create user
POST http://localhost:8000/v1/users
Content-Type: application/json

{
  "name": "Jane"
}

### Get user
GET http://localhost:8000/v1/users
Content-Type: application/json
Authorization: ApiKey {{user_api_key}}

### Create feed
POST http://localhost:8000/v1/feeds
Content-Type: application/json
Authorization: ApiKey {{user_api_key}}

{
  "name": "My Feed",
  "url": "https://google.com",
  "user_id": "d4d2ee1e-bd1a-4ef2-ae0a-d0d1d2d3d4d5"
}

### Get feeds
GET http://localhost:8000/v1/feeds

### Follow feed
POST http://localhost:8000/v1/feed_follows
Content-Type: application/json
Authorization: ApiKey {{user_api_key}}

{
  "feed_id": "0fd0c09d-4684-4e53-80ee-6c5eca8e21e0"
}

### Get feed follow
GET http://localhost:8000/v1/feed_follows
Content-Type: application/json
Authorization: ApiKey {{user_api_key}}

### Delete feed follow
DELETE http://localhost:8000/v1/feed_follows/9f34ae45-d594-4bed-a603-1f50e66d20b5
Content-Type: application/json
Authorization: ApiKey {{user_api_key}}

### Get posts
GET http://localhost:8000/v1/posts
Content-Type: application/json
Authorization: ApiKey {{user_api_key}}
