@user_api_key = <user_api_key>

### Health check
GET http://localhost:8000/v1/healthy

### Error
GET http://localhost:8000/v1/error

### Create user
POST http://localhost:8000/v1/users
Content-Type: application/json

{
  "name": "Jane"
}

### Get user
GET http://localhost:8000/v1/users
Content-Type: application/json
Authorization: ApiKey {{user_api_key}}

### Create feed
POST http://localhost:8000/v1/feeds
Content-Type: application/json
Authorization: ApiKey {{user_api_key}}

{
  "name": "My Feed",
  "url": "https://google.com",
  "user_id": "d4d2ee1e-bd1a-4ef2-ae0a-d0d1d2d3d4d5"
}

### Get feed
GET http://localhost:8000/v1/feeds

### Follow feed
POST http://localhost:8000/v1/feed_follows
Content-Type: application/json
Authorization: ApiKey {{user_api_key}}

{
  "feed_id": "efa8a450-b48a-4e46-9a68-5f980366cc70",
  "user_id": "1a0f8e5c-1ecb-4e39-96b5-840875b6b8e6"
}